import Head from 'next/head';

import styles from '../styles/Home.module.css';
import useSWR, { SWRConfig } from 'swr';

const fetcher = (url) => fetch(url).then((res) => res.json());
const API = 'https://api.github.com/repos/vercel/swr';

export async function getServerSideProps() {
	const repoInfo = await fetcher(API);
	return {
		props: {
			fallback: {
				'https://api.github.com/repos/vercel/swr': repoInfo
			}
		}
	};
}

function Posts() {
	const { data, error } = useSWR(API, fetcher);

	data && console.log(data);

	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main>
				<h1>
					Welcome to <a href="https://nextjs.org">Next.js!</a>
				</h1>
				<h1>{data?.name}</h1>
				<p>{data?.description}</p>
				<strong>👀 {data?.subscribers_count}</strong>{' '}
				<strong>✨ {data?.stargazers_count}</strong>{' '}
				<strong>🍴 {data?.forks_count}</strong>
			</main>
		</div>
	);
}

export default function Home({ fallback }) {
	// if (error) return 'An error has occurred.';
	// if (!data) return 'Loading...';

	return (
		<SWRConfig value={{ fallback }}>
			<Posts />
		</SWRConfig>
	);
}
